services:
  db:
    image: postgres:14
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deploy -d pixelnew_production"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pixelnew_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    environment:
      FRONTEND_URL: "https://nagovets.ru"
      REDIS_URL: "redis://redis:6379/0"  # Указываем адрес Redis для Docker
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/pixelnew_production
      RAILS_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: ["bash", "-c", "sleep 5 && bin/rails db:prepare && bundle exec puma -C config/puma.rb"]
    volumes:
      - .:/app
volumes:
  postgres_data:
