services:
  db:
    image: postgres:14
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deploy -d pixelnew_production"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pixelnew_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/pixelnew_production
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - .:/app
volumes:
  postgres_data:
