services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: <%= Rails.application.credentials.user_name %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.datebase %>
      POSTGRES_DB: pixelnew_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://<%= Rails.application.credentials.user_name %>:<%= Rails.application.credentials.database %>@db:5432/pixelnew_production
      RAILS_ENV: production
      SECRET_KEY_BASE: <%= Rails.application.credentials.secret_key_base %>
    volumes:
      - .:/app
volumes:
  postgres_data:
